# Generated by Django 4.0 on 2021-12-08 17:19

import Receipt.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipientName', models.CharField(max_length=30, validators=[Receipt.validators.validate_name])),
                ('recipientIban', models.CharField(max_length=29, validators=[Receipt.validators.validate_iban])),
                ('bank', models.CharField(choices=[('privatbank', 'privatbank'), ('universalbank', 'universalbank')], max_length=30)),
                ('paymentType', models.CharField(choices=[('handle', 'handle'), ('card', 'card'), ('NFC', 'NFC')], max_length=10)),
                ('amount', models.FloatField(validators=[Receipt.validators.validate_amount])),
                ('paymentDatetime', models.DateTimeField()),
            ],
        ),
    ]
